{
  "comments": [
    {
      "key": {
        "uuid": "d53531b0_cc2089e0",
        "filename": "components/pm-subscription-handler/pmsh_service/mod/pmsh_utils.py",
        "patchSetId": 2
      },
      "lineNbr": 68,
      "author": {
        "id": 105
      },
      "writtenOn": "2021-01-26T14:59:48Z",
      "side": 1,
      "message": "this appears to be a no-op",
      "revId": "734b861445639261069b066ca62d40d020930a16",
      "serverId": "14b4e41f-c4e3-4fb9-9955-6a9b5656895a",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "79cb9df6_08c914c1",
        "filename": "components/pm-subscription-handler/pmsh_service/mod/pmsh_utils.py",
        "patchSetId": 2
      },
      "lineNbr": 68,
      "author": {
        "id": 4405
      },
      "writtenOn": "2021-01-26T16:33:34Z",
      "side": 1,
      "message": "Ack",
      "parentUuid": "d53531b0_cc2089e0",
      "revId": "734b861445639261069b066ca62d40d020930a16",
      "serverId": "14b4e41f-c4e3-4fb9-9955-6a9b5656895a",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "57156aa3_c39e891b",
        "filename": "components/pm-subscription-handler/pmsh_service/mod/pmsh_utils.py",
        "patchSetId": 2
      },
      "lineNbr": 68,
      "author": {
        "id": 105
      },
      "writtenOn": "2021-01-27T18:30:32Z",
      "side": 1,
      "message": "+1",
      "parentUuid": "79cb9df6_08c914c1",
      "revId": "734b861445639261069b066ca62d40d020930a16",
      "serverId": "14b4e41f-c4e3-4fb9-9955-6a9b5656895a",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "fef2d50d_dec69e29",
        "filename": "components/pm-subscription-handler/pmsh_service/mod/pmsh_utils.py",
        "patchSetId": 2
      },
      "lineNbr": 119,
      "author": {
        "id": 105
      },
      "writtenOn": "2021-01-26T14:59:48Z",
      "side": 1,
      "message": "please update the syntax\nexcept (ValueError, Exception) as e:\n\npylint:\n W0711: Exception to catch is the result of a binary \"or\" operation (binary-op-exception)\n\n\nof course, there\u0027s the question of why ValueError is being listed separately when you\u0027re also catching Exception (a superclass of ValueError)? So for that, this could be simplified to\n\nexcept Exception as e:",
      "revId": "734b861445639261069b066ca62d40d020930a16",
      "serverId": "14b4e41f-c4e3-4fb9-9955-6a9b5656895a",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "2a3faff1_edf13a30",
        "filename": "components/pm-subscription-handler/pmsh_service/mod/pmsh_utils.py",
        "patchSetId": 2
      },
      "lineNbr": 119,
      "author": {
        "id": 4405
      },
      "writtenOn": "2021-01-26T16:33:34Z",
      "side": 1,
      "message": "Done",
      "parentUuid": "fef2d50d_dec69e29",
      "revId": "734b861445639261069b066ca62d40d020930a16",
      "serverId": "14b4e41f-c4e3-4fb9-9955-6a9b5656895a",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "2cafdc38_9242f27d",
        "filename": "components/pm-subscription-handler/pmsh_service/mod/pmsh_utils.py",
        "patchSetId": 2
      },
      "lineNbr": 119,
      "author": {
        "id": 105
      },
      "writtenOn": "2021-01-27T18:30:32Z",
      "side": 1,
      "message": "+1",
      "parentUuid": "2a3faff1_edf13a30",
      "revId": "734b861445639261069b066ca62d40d020930a16",
      "serverId": "14b4e41f-c4e3-4fb9-9955-6a9b5656895a",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "8fd416b6_206b670c",
        "filename": "components/pm-subscription-handler/pmsh_service/mod/pmsh_utils.py",
        "patchSetId": 2
      },
      "lineNbr": 221,
      "author": {
        "id": 105
      },
      "writtenOn": "2021-01-26T14:59:48Z",
      "side": 1,
      "message": "this except+raise appears to be a no-op\n\nany particular reason to keep it?\n\nif it\u0027s kept, change to a bare \"raise\" (which also eliminates the need to declare \u0027e\"",
      "revId": "734b861445639261069b066ca62d40d020930a16",
      "serverId": "14b4e41f-c4e3-4fb9-9955-6a9b5656895a",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "1467e25e_b9b86c1d",
        "filename": "components/pm-subscription-handler/pmsh_service/mod/pmsh_utils.py",
        "patchSetId": 2
      },
      "lineNbr": 221,
      "author": {
        "id": 4405
      },
      "writtenOn": "2021-01-26T16:33:34Z",
      "side": 1,
      "message": "Yep, I will raise it up the call stack so. Missed that.\nAgain, we will revsit our exception handling asap.",
      "parentUuid": "8fd416b6_206b670c",
      "revId": "734b861445639261069b066ca62d40d020930a16",
      "serverId": "14b4e41f-c4e3-4fb9-9955-6a9b5656895a",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "3d5e9ebd_1ca2fdc3",
        "filename": "components/pm-subscription-handler/pmsh_service/mod/pmsh_utils.py",
        "patchSetId": 2
      },
      "lineNbr": 221,
      "author": {
        "id": 105
      },
      "writtenOn": "2021-01-27T18:30:32Z",
      "side": 1,
      "message": "Ack",
      "parentUuid": "1467e25e_b9b86c1d",
      "revId": "734b861445639261069b066ca62d40d020930a16",
      "serverId": "14b4e41f-c4e3-4fb9-9955-6a9b5656895a",
      "unresolved": false
    }
  ]
}